// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// integrandSteady
double integrandSteady(double U, double V, double L, double lambda, int mm, double nu, double ubc, int tmin, int tmax);
RcppExport SEXP _PH2EWMA_integrandSteady(SEXP USEXP, SEXP VSEXP, SEXP LSEXP, SEXP lambdaSEXP, SEXP mmSEXP, SEXP nuSEXP, SEXP ubcSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type ubc(ubcSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(integrandSteady(U, V, L, lambda, mm, nu, ubc, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// qintegrandSteady
int qintegrandSteady(double q, double U, double V, double L, double lambda, int mm, double nu, double ubc, int tmin, int tmax);
RcppExport SEXP _PH2EWMA_qintegrandSteady(SEXP qSEXP, SEXP USEXP, SEXP VSEXP, SEXP LSEXP, SEXP lambdaSEXP, SEXP mmSEXP, SEXP nuSEXP, SEXP ubcSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type ubc(ubcSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(qintegrandSteady(q, U, V, L, lambda, mm, nu, ubc, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// integrandZero
double integrandZero(double U, double V, double L, double lambda, int mm, double nu, int nn, double ubc, int tmin, int tmax);
RcppExport SEXP _PH2EWMA_integrandZero(SEXP USEXP, SEXP VSEXP, SEXP LSEXP, SEXP lambdaSEXP, SEXP mmSEXP, SEXP nuSEXP, SEXP nnSEXP, SEXP ubcSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< double >::type ubc(ubcSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(integrandZero(U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// qintegrandZero
int qintegrandZero(double q, double U, double V, double L, double lambda, int mm, double nu, int nn, double ubc, int tmin, int tmax);
RcppExport SEXP _PH2EWMA_qintegrandZero(SEXP qSEXP, SEXP USEXP, SEXP VSEXP, SEXP LSEXP, SEXP lambdaSEXP, SEXP mmSEXP, SEXP nuSEXP, SEXP nnSEXP, SEXP ubcSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< double >::type ubc(ubcSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(qintegrandZero(q, U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
