# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrandSteady <- function(U, V, L, lambda, mm, nu, ubc, tmin, tmax) {
    .Call(`_PH2EWMA_integrandSteady`, U, V, L, lambda, mm, nu, ubc, tmin, tmax)
}

qintegrandSteady <- function(q, U, V, L, lambda, mm, nu, ubc, tmin, tmax) {
    .Call(`_PH2EWMA_qintegrandSteady`, q, U, V, L, lambda, mm, nu, ubc, tmin, tmax)
}

integrandZero <- function(U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax) {
    .Call(`_PH2EWMA_integrandZero`, U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax)
}

qintegrandZero <- function(q, U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax) {
    .Call(`_PH2EWMA_qintegrandZero`, q, U, V, L, lambda, mm, nu, nn, ubc, tmin, tmax)
}

